version: 2.1

parameters:
  build-bitwarden-serve:
    type: boolean
    default: false

commands:
  build-image:
    description: "Build a docker image"
    parameters:
      app:
        description: The name of the app
        type: string
      context:
        description: "The folder to build in"
        type: string
        default: "."
      dockerfile:
        description: "Use to override Dockerfile path"
        type: string
        default: "Dockerfile"
      tag:
        description: "Use to set tag, default: rolling"
        type: string
        default: "rolling"
      latest:
        description: "Use the latest tag, options: true, false, auto (auto will use latest if branch is main)"
        type: string
        default: "auto"
      push:
        description: "Check if image should be pushed to registry"
        type: boolean
        default: true
    steps:
      - run:
          name: Login to registries
          command: |
            echo "Logging in to Docker Hub"
            echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin docker.io
            echo "Logging in to ghcr.io"
            echo "${GHCR_TOKEN}" | docker login -u "${GHCR_USER}" --password-stdin ghcr.io
      - run:
          name: debug
          command: |
            echo "Building ${CIRCLE_JOB} for ${CIRCLE_BRANCH}"
            echo "App: << parameters.app >>"
            echo "Context: << parameters.context >>"
            echo "Dockerfile: << parameters.dockerfile >>"
            echo "Tag: << parameters.tag >>"
            echo "Latest: << parameters.latest >>"
      - run:
          name: Build and push images
          command: |
            tags="<< parameters.tag >>"
            if [ "<< parameters.event.name >>" != "pull_request" ] && [ "<< parameters.latest >> " == "auto" ]; then
              tags="${tags} latest"
            elif [ "<< parameters.latest >>" == "true" ]; then
              tags="${tags} latest"
            fi

            names=""
            for tag in $tags; do
              names="${names} ghcr.io/${GHCR_USER}/<< parameters.app >>:${tag} docker.io/${DOCKER_USER}/<< parameters.app >>:${tag}"
            done

            cd << parameters.context >>

            for name in $names; do
              TMP_IMAGES=""
              for arch in amd64 arm64; do
                echo "Building ${name} for ${arch}"
                docker build --platform linux/${arch} \
                  -f << parameters.dockerfile >> \
                  -t "${name}-${arch}" \
                  .
                TMP_IMAGES="${TMP_IMAGES} ${name}-${arch}"
              done
              docker manifest create --amend "${name}" ${TMP_IMAGES}
            done

jobs:
  build-bitwarden-serve:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Metadata
          command: |
            set -ex
            VERSION_STRING="$(grep "ENV BW_CLI_VERSION=" apps/bitwarden-serve/Dockerfile)"
            VERSION="$(echo "${VERSION_STRING}" | awk -F'=' '{print $2}' | tr -d '"')"
            echo "export VERSION=${VERSION#cli-}" >> $BASH_ENV
      - build-image:
          app: bitwarden-serve
          context: apps/bitwarden-serve
          tag: ${VERSION}

workflows:
  bitwarden-serve:
    when: << pipeline.parameters.build-bitwarden-serve >>
    context:
      - docker
    jobs:
      - build-bitwarden-serve
