FROM quay.io/fedora/fedora-coreos:stable@sha256:456b8952e54ebefcd8a1c223535aa9f34f8c092f4ae9f34abfcefb94a261e248

LABEL   org.opencontainers.image.authors="heathcliff@heathcliff.eu" \
        org.opencontainers.image.description="Fedora CoreOS with Kubernetes and CRI-O" \
        org.opencontainers.image.source="https://github.com/heathcliff26/containers/tree/main/apps/fcos-k8s" \
        org.opencontainers.image.licenses="Apache-2.0" \
        org.opencontainers.image.title="fcos-k8s"

LABEL quay.expires-after=2y

# renovate: datasource=github-tags depName=kubernetes/kubernetes extractVersion=^v(?<version>.*)$
ENV KUBERNETES_VERSION=1.34.3

ENV CRIO_VERSION=1.34

COPY k8s-install.sh migration-remove-upgraded.service /var/kubernetes/

RUN /var/kubernetes/k8s-install.sh
