FROM quay.io/fedora/fedora-coreos:stable@sha256:b084c5178fd1eaaf3adefab886591ed9e1da992101358298bff87deeae82dd4b

# renovate: datasource=github-tags depName=kubernetes/kubernetes extractVersion=^v(?<version>.*)$
ENV KUBERNETES_VERSION=1.30.5

# TODO: Switch to actual crio version once 41 hits stable
ENV CRIO_VERSION=""

# renovate: datasource=github-releases depName=heathcliff26/kube-upgrade extractVersion=^(?<version>.*)$
ENV KUBE_UPGRADE_VERSION=v0.3.1

COPY k8s-install.sh upgraded.service  /var/kubernetes/

RUN /var/kubernetes/k8s-install.sh
