FROM quay.io/fedora/fedora-coreos:stable@sha256:8a38d67c0366265d7b2a5417254f3ba4f6958a55af07aa11f899c14ef4ca3d64

# renovate: datasource=github-tags depName=kubernetes/kubernetes extractVersion=^v(?<version>.*)$
ENV KUBERNETES_VERSION=1.30.9

ENV CRIO_VERSION=1.30

# renovate: datasource=github-releases depName=heathcliff26/kube-upgrade extractVersion=^(?<version>.*)$
ENV KUBE_UPGRADE_VERSION=v0.4.4

COPY k8s-install.sh upgraded.service /var/kubernetes/

RUN /var/kubernetes/k8s-install.sh
