FROM quay.io/fedora/fedora-coreos:stable@sha256:525b4a92ff363085aad35c7a8b7d46588172f2fa119c78d075a1c3546869ede2

# renovate: datasource=github-tags depName=kubernetes/kubernetes extractVersion=^v(?<version>.*)$
ENV KUBERNETES_VERSION=1.30.10

ENV CRIO_VERSION=1.30

# renovate: datasource=github-releases depName=heathcliff26/kube-upgrade extractVersion=^(?<version>.*)$
ENV KUBE_UPGRADE_VERSION=v0.4.5

COPY k8s-install.sh upgraded.service /var/kubernetes/

RUN /var/kubernetes/k8s-install.sh
