---
name: Build squid

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/squid/Dockerfile"
      - "apps/squid/*.sh"
  pull_request:
    branches: [main]
    paths:
      - "apps/squid/Dockerfile"
      - "apps/squid/*.sh"
      - ".github/workflows/build-squid.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      app: squid
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      context: apps/squid
    secrets: inherit
