---
name: Build unbound

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/unbound/Dockerfile"
      - "apps/unbound/*.sh"
  pull_request:
    branches: [main]
    paths:
      - "apps/unbound/Dockerfile"
      - "apps/unbound/*.sh"
      - ".github/workflows/build-unbound.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    with:
      app: unbound
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets: inherit
