---
name: Build unbound

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/unbound/Dockerfile"
      - "apps/unbound/*.sh"
  pull_request:
    branches: [main]
    paths:
      - "apps/unbound/Dockerfile"
      - "apps/unbound/*.sh"
      - ".github/workflows/build-unbound.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@42ac7a8dcdf67ef1e18a0082966072cce75a0fe4 # main
    permissions:
      contents: read
      packages: write
    with:
      app: unbound
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      context: apps/unbound
    secrets: inherit
