---
name: Build alpine-abuild

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/alpine-abuild/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "apps/alpine-abuild/Dockerfile"
      - ".github/workflows/build-alpine-abuild.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      app: alpine-abuild
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      context: apps/alpine-abuild
    secrets: inherit
