---
name: Build cloudflare-dyndns

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/cloudflare-dyndns/Dockerfile"
      - "apps/cloudflare-dyndns/*.go"
      - "apps/cloudflare-dyndns/go.mod"
      - "apps/cloudflare-dyndns/go.sum"
      - "apps/cloudflare-dyndns/**/*.go"
  pull_request:
    branches: [main]
    paths:
      - "apps/cloudflare-dyndns/Dockerfile"
      - "apps/cloudflare-dyndns/*.go"
      - "apps/cloudflare-dyndns/go.mod"
      - "apps/cloudflare-dyndns/go.sum"
      - "apps/cloudflare-dyndns/**/*.go"
      - ".github/workflows/build-cloudflare-dyndns.yaml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 'stable'
          cache-dependency-path: apps/cloudflare-dyndns/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          working-directory: apps/cloudflare-dyndns
          args: --config=.golangci.yml
          skip-cache: true

  build:
    uses: ./.github/workflows/build.yaml
    needs: golangci
    permissions:
      contents: read
      packages: write
    with:
      app: cloudflare-dyndns
      dockerfile: Dockerfile
      tag: slim
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets: inherit
