---
name: Build go-fyne-ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/go-fyne-ci/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "apps/go-fyne-ci/Dockerfile"
      - ".github/workflows/build-go-fyne-ci.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    with:
      app: go-fyne-ci
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    secrets: inherit
