---
name: Build speedtest-exporter

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/speedtest-exporter/Dockerfile"
      - "apps/speedtest-exporter/Dockerfile.cli"
      - "apps/speedtest-exporter/*.go"
  pull_request:
    branches: [main]
    paths:
      - "apps/speedtest-exporter/Dockerfile"
      - "apps/speedtest-exporter/Dockerfile.cli"
      - "apps/speedtest-exporter/*.go"
      - ".github/workflows/build-speedtest-exporter.yaml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-go@v4.1.0
        with:
          go-version: 'stable'
          cache-dependency-path: apps/speedtest-exporter/go.sum

      - name: debug
        run: |
          pwd
          ls -lha
          ls -lha containers

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          working-directory: apps/speedtest-exporter
          args: --config=containers/apps/speedtest-exporter/.golangci.yml

  build:
    uses: ./.github/workflows/build.yaml
    needs: golangci
    permissions:
      contents: read
      packages: write
    with:
      app: speedtest-exporter
      dockerfile: Dockerfile
      tag: native
      #dry-run: ${{ github.event_name == 'pull_request' }}
      dry-run: true
    secrets: inherit

  build-cli:
    uses: ./.github/workflows/build.yaml
    needs: golangci
    permissions:
      contents: read
      packages: write
    with:
      app: speedtest-exporter
      dockerfile: Dockerfile.cli
      tag: cli
      #dry-run: ${{ github.event_name == 'pull_request' }}
      dry-run: true
    secrets: inherit
