---
name: Build go-fyne-ci

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/go-fyne-ci/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "apps/go-fyne-ci/Dockerfile"
      - ".github/workflows/build-go-fyne-ci.yaml"
  merge_group:
    branches: ["main"]

jobs:
  metadata:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
    outputs:
      version: "${{ steps.version.outputs.version }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Extract bitwarden-cli version
        id: version
        run: |
          set -ex
          VERSION="$(grep "FROM docker.io/library/golang" apps/go-fyne-ci/Dockerfile | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+")"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    needs: metadata
    permissions:
      contents: read
      packages: write
    with:
      app: go-fyne-ci
      tag: "${{ needs.metadata.outputs.version }}"
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      context: apps/go-fyne-ci
    secrets: inherit
