---
name: Build github-actions-runner

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/github-actions-runner/Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "apps/github-actions-runner/Dockerfile"
      - ".github/workflows/build-github-actions-runner.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      app: github-actions-runner
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      context: apps/github-actions-runner
    secrets: inherit
