---
name: Build default-webpage

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - "apps/default-webpage/Dockerfile"
      - "apps/default-webpage/*.html"
      - "apps/default-webpage/**/*.html"
  pull_request:
    branches: [main]
    paths:
      - "apps/default-webpage/Dockerfile"
      - "apps/default-webpage/*.html"
      - "apps/default-webpage/**/*.html"
      - ".github/workflows/build-default-webpage.yaml"
  merge_group:
    branches: ["main"]

jobs:
  build-tiny:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    with:
      app: default-webpage
      dockerfile: Dockerfile
      tag: slim
      tags: |
        rolling"
        "type=raw,value=latest,enable={{is_default_branch}}
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets: inherit

  build-nginx:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    with:
      app: default-webpage
      dockerfile: Dockerfile.nginx
      tag: nginx
      tags: ""
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets: inherit
