---
name: "Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check-links:
    uses: heathcliff26/ci/.github/workflows/link-check.yaml@42ac7a8dcdf67ef1e18a0082966072cce75a0fe4 # main
    secrets: inherit
    permissions: {}
    with:
      exclude-links: "gitlab.alpinelinux.org/alpine/infra/docker/unbound"
