---
name: Prune ghcr.io

on:
  workflow_dispatch:
    inputs:
      app:
        description: "The name of the app"
        type: string
        required: true
      keep:
        description: "The number of versions to keep"
        type: string
        default: "50"
        required: true
      delete-tagged:
        description: "Delete tagged versions"
        type: boolean
        default: false
      ignore-versions:
        description: "Versions to ignore"
        type: string
        default: "(latest|rolling)"
        required: false

jobs:
  prune:
    uses: heathcliff26/ci/.github/workflows/prune-ghcr.yaml@main
    permissions:
      packages: write
    with:
      app: "${{ inputs.app }}"
      keep: "${{ inputs.keep }}"
      ignore-versions: "${{ inputs.ignore-versions }}"
      delete-tagged: ${{ inputs.delete-tagged }}
