---
name: Test go-fyne-ci

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]
    paths:
      - "apps/go-fyne-ci/Dockerfile"
      - "apps/go-fyne-ci/test.sh"
      - ".github/workflows/test-go-fyne-ci.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run test script
        run: apps/go-fyne-ci/test.sh
